name: time_picker_sheet
description: Time picker sheet library, allows you to have beauty time picker sheet with customizable design to align with your requirements.
homepage: https://github.com/jesims/time-picker-sheet
version: 1.0.0+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
